# Form implementation generated from reading ui file 'C:\Users\gilya\Projects\PyCharm\ORIS-tasks\strategy_game\modules\gui\player_list_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlayerListItem(object):
    def setupUi(self, PlayerListItem):
        PlayerListItem.setObjectName("PlayerListItem")
        PlayerListItem.resize(128, 28)
        PlayerListItem.setMinimumSize(QtCore.QSize(0, 28))
        PlayerListItem.setStyleSheet("#PlayerListItem {\n"
"    background-color: #C9CBCF;\n"
"    border-radius: 10px;\n"
"}\n"
"#PlayerListItem:hover {background-color: #B3B6BC}\n"
"#PlayerListItem[selected=true] {background-color: #85D2FF}\n"
"#PlayerListItem[selected=true]:hover {background-color: #5CC3FF}\n"
"\n"
"QLabel {\n"
"    color: black;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"QMenu::item, QMenu::icon {\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #EAECEC;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(PlayerListItem)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_username = QtWidgets.QLabel(parent=PlayerListItem)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.icon_host = QtWidgets.QLabel(parent=PlayerListItem)
        self.icon_host.setPixmap(QtGui.QPixmap("res:/icons/host.png"))
        self.icon_host.setObjectName("icon_host")
        self.horizontalLayout.addWidget(self.icon_host)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(PlayerListItem)
        QtCore.QMetaObject.connectSlotsByName(PlayerListItem)

    def retranslateUi(self, PlayerListItem):
        _translate = QtCore.QCoreApplication.translate
        PlayerListItem.setWindowTitle(_translate("PlayerListItem", "Form"))
        self.label_username.setText(_translate("PlayerListItem", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlayerListItem = QtWidgets.QWidget()
    ui = Ui_PlayerListItem()
    ui.setupUi(PlayerListItem)
    PlayerListItem.show()
    sys.exit(app.exec())
