# Form implementation generated from reading ui file 'C:\Users\gilya\Projects\PyCharm\ORIS-tasks\strategy_game\modules\gui\room_browser.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RoomBrowser(object):
    def setupUi(self, RoomBrowser):
        RoomBrowser.setObjectName("RoomBrowser")
        RoomBrowser.resize(500, 300)
        RoomBrowser.setMinimumSize(QtCore.QSize(500, 300))
        RoomBrowser.setStyleSheet("#RoomBrowser, QScrollArea QWidget {background-color: #DFE0E2}\n"
"\n"
"QLabel {\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit, QPushButton {\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 4px;\n"
"    height: 16px;\n"
"}\n"
"QLineEdit {background-color: white}\n"
"QPushButton {background-color: #85D2FF}\n"
"QPushButton:hover {background-color: #5CC3FF}\n"
"QPushButton:disabled {\n"
"    background-color: #D6F0FF;\n"
"    color: #40404F;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    border: 1px solid #9EA1A9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QScrollBar,\n"
"QScrollBar::sub-line, QScrollBar::sub-page,\n"
"QScrollBar::add-line, QScrollBar::add-page\n"
"{\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle {\n"
"    background-color: #9EA1A9;\n"
"    border-radius: 2px;\n"
"    margin: 6px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    border-radius: 4px;\n"
"    margin: 4px;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(RoomBrowser)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.input_playercount = QtWidgets.QSpinBox(parent=RoomBrowser)
        self.input_playercount.setMinimumSize(QtCore.QSize(40, 0))
        self.input_playercount.setMinimum(2)
        self.input_playercount.setMaximum(4)
        self.input_playercount.setProperty("value", 4)
        self.input_playercount.setObjectName("input_playercount")
        self.gridLayout.addWidget(self.input_playercount, 1, 2, 1, 1)
        self.btn_join = QtWidgets.QPushButton(parent=RoomBrowser)
        self.btn_join.setEnabled(False)
        self.btn_join.setObjectName("btn_join")
        self.gridLayout.addWidget(self.btn_join, 6, 1, 1, 2)
        self.input_mapsize = QtWidgets.QSpinBox(parent=RoomBrowser)
        self.input_mapsize.setMinimum(8)
        self.input_mapsize.setMaximum(32)
        self.input_mapsize.setProperty("value", 16)
        self.input_mapsize.setObjectName("input_mapsize")
        self.gridLayout.addWidget(self.input_mapsize, 2, 2, 1, 1)
        self.input_roomname = QtWidgets.QLineEdit(parent=RoomBrowser)
        self.input_roomname.setMinimumSize(QtCore.QSize(0, 0))
        self.input_roomname.setObjectName("input_roomname")
        self.gridLayout.addWidget(self.input_roomname, 0, 1, 1, 2)
        self.label_playercount = QtWidgets.QLabel(parent=RoomBrowser)
        self.label_playercount.setMinimumSize(QtCore.QSize(70, 0))
        self.label_playercount.setObjectName("label_playercount")
        self.gridLayout.addWidget(self.label_playercount, 1, 1, 1, 1)
        self.btn_create = QtWidgets.QPushButton(parent=RoomBrowser)
        self.btn_create.setObjectName("btn_create")
        self.gridLayout.addWidget(self.btn_create, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(parent=RoomBrowser)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=RoomBrowser)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 301, 268))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_roomlist = QtWidgets.QVBoxLayout()
        self.layout_roomlist.setSpacing(3)
        self.layout_roomlist.setObjectName("layout_roomlist")
        self.verticalLayout.addLayout(self.layout_roomlist)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 8, 1)
        self.btn_disconnect = QtWidgets.QPushButton(parent=RoomBrowser)
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.gridLayout.addWidget(self.btn_disconnect, 7, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 2)
        self.input_startingmoney = QtWidgets.QSpinBox(parent=RoomBrowser)
        self.input_startingmoney.setMaximum(9999)
        self.input_startingmoney.setSingleStep(10)
        self.input_startingmoney.setProperty("value", 100)
        self.input_startingmoney.setObjectName("input_startingmoney")
        self.gridLayout.addWidget(self.input_startingmoney, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=RoomBrowser)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(RoomBrowser)
        QtCore.QMetaObject.connectSlotsByName(RoomBrowser)

    def retranslateUi(self, RoomBrowser):
        _translate = QtCore.QCoreApplication.translate
        RoomBrowser.setWindowTitle(_translate("RoomBrowser", "Form"))
        self.btn_join.setText(_translate("RoomBrowser", "Join room"))
        self.input_roomname.setPlaceholderText(_translate("RoomBrowser", "Room name"))
        self.label_playercount.setText(_translate("RoomBrowser", "Max players"))
        self.btn_create.setText(_translate("RoomBrowser", "Create room"))
        self.label.setText(_translate("RoomBrowser", "Map size"))
        self.btn_disconnect.setText(_translate("RoomBrowser", "Disconnect"))
        self.label_2.setText(_translate("RoomBrowser", "Starting money"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoomBrowser = QtWidgets.QWidget()
    ui = Ui_RoomBrowser()
    ui.setupUi(RoomBrowser)
    RoomBrowser.show()
    sys.exit(app.exec())
