# Form implementation generated from reading ui file 'C:\Users\gilya\Projects\PyCharm\ORIS-tasks\word_game\modules\gui\menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(223, 126)
        self.menu_layout = QtWidgets.QGridLayout(Menu)
        self.menu_layout.setObjectName("menu_layout")
        self.btn_host = QtWidgets.QPushButton(parent=Menu)
        self.btn_host.setObjectName("btn_host")
        self.menu_layout.addWidget(self.btn_host, 3, 0, 1, 1)
        self.input_address = QtWidgets.QLineEdit(parent=Menu)
        self.input_address.setObjectName("input_address")
        self.menu_layout.addWidget(self.input_address, 2, 0, 1, 2)
        self.input_password = QtWidgets.QLineEdit(parent=Menu)
        self.input_password.setObjectName("input_password")
        self.menu_layout.addWidget(self.input_password, 1, 0, 1, 2)
        self.input_username = QtWidgets.QLineEdit(parent=Menu)
        self.input_username.setObjectName("input_username")
        self.menu_layout.addWidget(self.input_username, 0, 0, 1, 2)
        self.btn_connect = QtWidgets.QPushButton(parent=Menu)
        self.btn_connect.setObjectName("btn_connect")
        self.menu_layout.addWidget(self.btn_connect, 3, 1, 1, 1)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.btn_host.setText(_translate("Menu", "Host server"))
        self.input_address.setText(_translate("Menu", "127.0.0.1:54321"))
        self.input_address.setPlaceholderText(_translate("Menu", "Server address"))
        self.input_password.setPlaceholderText(_translate("Menu", "Password"))
        self.input_username.setPlaceholderText(_translate("Menu", "Username"))
        self.btn_connect.setText(_translate("Menu", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec())
