# Form implementation generated from reading ui file 'C:\Users\gilya\Projects\PyCharm\ORIS-tasks\word_game\modules\gui\server.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName("Server")
        Server.resize(500, 300)
        Server.setMinimumSize(QtCore.QSize(500, 300))
        Server.setStyleSheet("#Server, QScrollArea QWidget {background-color: #DFE0E2}\n"
"\n"
"QPushButton {\n"
"    color: black;\n"
"    background-color: #85D2FF;\n"
"    border-radius: 10px;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton:hover {background-color: #5CC3FF}\n"
"QPushButton:disabled {\n"
"    background-color: #D6F0FF;\n"
"    color: #40404F;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    border: 1px solid #9EA1A9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QScrollBar,\n"
"QScrollBar::sub-line, QScrollBar::sub-page,\n"
"QScrollBar::add-line, QScrollBar::add-page\n"
"{\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle {\n"
"    background-color: #9EA1A9;\n"
"    border-radius: 2px;\n"
"    margin: 6px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    border-radius: 4px;\n"
"    margin: 4px;\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Server)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=Server)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Server)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 2)
        self.label_players_in_rooms = QtWidgets.QLabel(parent=Server)
        self.label_players_in_rooms.setMinimumSize(QtCore.QSize(30, 16))
        self.label_players_in_rooms.setMaximumSize(QtCore.QSize(30, 16))
        self.label_players_in_rooms.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_players_in_rooms.setObjectName("label_players_in_rooms")
        self.gridLayout_2.addWidget(self.label_players_in_rooms, 3, 3, 1, 1)
        self.label_player_count = QtWidgets.QLabel(parent=Server)
        self.label_player_count.setMinimumSize(QtCore.QSize(30, 16))
        self.label_player_count.setMaximumSize(QtCore.QSize(30, 16))
        self.label_player_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_player_count.setObjectName("label_player_count")
        self.gridLayout_2.addWidget(self.label_player_count, 2, 3, 1, 1)
        self.btn_stop = QtWidgets.QPushButton(parent=Server)
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout_2.addWidget(self.btn_stop, 4, 2, 1, 2)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=Server)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(160, 0))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollList = QtWidgets.QWidget()
        self.scrollList.setGeometry(QtCore.QRect(0, 0, 131, 172))
        self.scrollList.setObjectName("scrollList")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollList)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layout_playerlist = QtWidgets.QVBoxLayout()
        self.layout_playerlist.setSpacing(3)
        self.layout_playerlist.setObjectName("layout_playerlist")
        self.verticalLayout_3.addLayout(self.layout_playerlist)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.scrollArea_2.setWidget(self.scrollList)
        self.gridLayout_2.addWidget(self.scrollArea_2, 1, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=Server)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=Server)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollList_2 = QtWidgets.QWidget()
        self.scrollList_2.setGeometry(QtCore.QRect(0, 0, 281, 268))
        self.scrollList_2.setObjectName("scrollList_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollList_2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_roomlist = QtWidgets.QVBoxLayout()
        self.layout_roomlist.setSpacing(3)
        self.layout_roomlist.setObjectName("layout_roomlist")
        self.verticalLayout.addLayout(self.layout_roomlist)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollList_2)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 5, 1)

        self.retranslateUi(Server)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        _translate = QtCore.QCoreApplication.translate
        Server.setWindowTitle(_translate("Server", "Form"))
        self.label.setText(_translate("Server", "Players connected:"))
        self.label_3.setText(_translate("Server", "Players browsing:"))
        self.label_players_in_rooms.setText(_translate("Server", "0"))
        self.label_player_count.setText(_translate("Server", "0"))
        self.btn_stop.setText(_translate("Server", "Stop Server"))
        self.label_2.setText(_translate("Server", "Players in rooms:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Server = QtWidgets.QWidget()
    ui = Ui_Server()
    ui.setupUi(Server)
    Server.show()
    sys.exit(app.exec())
