# Form implementation generated from reading ui file 'C:\Users\gilya\Projects\PyCharm\ORIS-tasks\word_game\gui\room_browser.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RoomBrowser(object):
    def setupUi(self, RoomBrowser):
        RoomBrowser.setObjectName("RoomBrowser")
        RoomBrowser.resize(400, 200)
        RoomBrowser.setMinimumSize(QtCore.QSize(400, 200))
        self.layout_browser = QtWidgets.QHBoxLayout(RoomBrowser)
        self.layout_browser.setObjectName("layout_browser")
        self.scrollArea = QtWidgets.QScrollArea(parent=RoomBrowser)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 237, 180))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_roomlist = QtWidgets.QVBoxLayout()
        self.layout_roomlist.setSpacing(3)
        self.layout_roomlist.setObjectName("layout_roomlist")
        self.verticalLayout.addLayout(self.layout_roomlist)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_browser.addWidget(self.scrollArea)
        self.layout_sidepanel = QtWidgets.QVBoxLayout()
        self.layout_sidepanel.setObjectName("layout_sidepanel")
        self.layout_create_room = QtWidgets.QGridLayout()
        self.layout_create_room.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.layout_create_room.setObjectName("layout_create_room")
        self.input_playercount = QtWidgets.QSpinBox(parent=RoomBrowser)
        self.input_playercount.setMinimumSize(QtCore.QSize(40, 0))
        self.input_playercount.setMinimum(2)
        self.input_playercount.setMaximum(64)
        self.input_playercount.setProperty("value", 8)
        self.input_playercount.setObjectName("input_playercount")
        self.layout_create_room.addWidget(self.input_playercount, 1, 1, 1, 1)
        self.btn_create = QtWidgets.QPushButton(parent=RoomBrowser)
        self.btn_create.setObjectName("btn_create")
        self.layout_create_room.addWidget(self.btn_create, 2, 0, 1, 2)
        self.label_playercount = QtWidgets.QLabel(parent=RoomBrowser)
        self.label_playercount.setMinimumSize(QtCore.QSize(70, 0))
        self.label_playercount.setObjectName("label_playercount")
        self.layout_create_room.addWidget(self.label_playercount, 1, 0, 1, 1)
        self.input_roomname = QtWidgets.QLineEdit(parent=RoomBrowser)
        self.input_roomname.setMinimumSize(QtCore.QSize(0, 0))
        self.input_roomname.setObjectName("input_roomname")
        self.layout_create_room.addWidget(self.input_roomname, 0, 0, 1, 2)
        self.layout_sidepanel.addLayout(self.layout_create_room)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.layout_sidepanel.addItem(spacerItem1)
        self.btn_join = QtWidgets.QPushButton(parent=RoomBrowser)
        self.btn_join.setEnabled(False)
        self.btn_join.setObjectName("btn_join")
        self.layout_sidepanel.addWidget(self.btn_join)
        self.layout_browser.addLayout(self.layout_sidepanel)

        self.retranslateUi(RoomBrowser)
        QtCore.QMetaObject.connectSlotsByName(RoomBrowser)

    def retranslateUi(self, RoomBrowser):
        _translate = QtCore.QCoreApplication.translate
        RoomBrowser.setWindowTitle(_translate("RoomBrowser", "Form"))
        self.btn_create.setText(_translate("RoomBrowser", "Create room"))
        self.label_playercount.setText(_translate("RoomBrowser", "Max players"))
        self.input_roomname.setPlaceholderText(_translate("RoomBrowser", "Room name"))
        self.btn_join.setText(_translate("RoomBrowser", "Join room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoomBrowser = QtWidgets.QWidget()
    ui = Ui_RoomBrowser()
    ui.setupUi(RoomBrowser)
    RoomBrowser.show()
    sys.exit(app.exec())
